// Las 64 selecciones del Fixture 2030: las 48 del Mundial 2026 (grupos A-L) mas
// 16 que completan los cupos por confederacion (grupos M-P).
//
// Se distribuye como .js y no como .json porque mongosh carga JavaScript con
// load() de forma nativa, sin depender de mongoimport.
//
// `anfitrion` marca las seis sedes: Espana, Portugal y Marruecos como
// organizadores, mas Uruguay, Argentina y Paraguay por los partidos del
// centenario.

globalThis.EQUIPOS = [
  { _id: "MEX", nombre: "Mexico",                 confederacion: "CONCACAF", grupo: "A", ranking_fifa: 16, participaciones_mundiales: 17, director_tecnico: "Javier Aguirre",        anfitrion: false },
  { _id: "KOR", nombre: "Corea del Sur",          confederacion: "AFC",      grupo: "A", ranking_fifa: 21, participaciones_mundiales: 11, director_tecnico: "Hong Myung-bo",         anfitrion: false },
  { _id: "RSA", nombre: "Sudafrica",              confederacion: "CAF",      grupo: "A", ranking_fifa: 36, participaciones_mundiales:  4, director_tecnico: "Hugo Broos",            anfitrion: false },
  { _id: "CZE", nombre: "Chequia",                confederacion: "UEFA",     grupo: "A", ranking_fifa: 42, participaciones_mundiales:  9, director_tecnico: "Ivan Hasek",            anfitrion: false },
  { _id: "CAN", nombre: "Canada",                 confederacion: "CONCACAF", grupo: "B", ranking_fifa: 38, participaciones_mundiales:  3, director_tecnico: "Jesse Marsch",          anfitrion: false },
  { _id: "BIH", nombre: "Bosnia y Herzegovina",   confederacion: "UEFA",     grupo: "B", ranking_fifa: 58, participaciones_mundiales:  1, director_tecnico: "Sergej Barbarez",       anfitrion: false },
  { _id: "QAT", nombre: "Catar",                  confederacion: "AFC",      grupo: "B", ranking_fifa: 48, participaciones_mundiales:  2, director_tecnico: "Luis Garcia Plaza",     anfitrion: false },
  { _id: "SUI", nombre: "Suiza",                  confederacion: "UEFA",     grupo: "B", ranking_fifa: 17, participaciones_mundiales: 12, director_tecnico: "Murat Yakin",           anfitrion: false },
  { _id: "BRA", nombre: "Brasil",                 confederacion: "CONMEBOL", grupo: "C", ranking_fifa:  5, participaciones_mundiales: 22, director_tecnico: "Carlo Ancelotti",       anfitrion: false },
  { _id: "MAR", nombre: "Marruecos",              confederacion: "CAF",      grupo: "C", ranking_fifa: 12, participaciones_mundiales:  6, director_tecnico: "Walid Regragui",        anfitrion: true  },
  { _id: "HAI", nombre: "Haiti",                  confederacion: "CONCACAF", grupo: "C", ranking_fifa: 62, participaciones_mundiales:  2, director_tecnico: "Sebastien Migne",       anfitrion: false },
  { _id: "SCO", nombre: "Escocia",                confederacion: "UEFA",     grupo: "C", ranking_fifa: 37, participaciones_mundiales:  8, director_tecnico: "Steve Clarke",          anfitrion: false },
  { _id: "USA", nombre: "Estados Unidos",         confederacion: "CONCACAF", grupo: "D", ranking_fifa: 15, participaciones_mundiales: 11, director_tecnico: "Mauricio Pochettino",   anfitrion: false },
  { _id: "PAR", nombre: "Paraguay",               confederacion: "CONMEBOL", grupo: "D", ranking_fifa: 43, participaciones_mundiales:  8, director_tecnico: "Gustavo Alfaro",        anfitrion: true  },
  { _id: "AUS", nombre: "Australia",              confederacion: "AFC",      grupo: "D", ranking_fifa: 27, participaciones_mundiales:  6, director_tecnico: "Tony Popovic",          anfitrion: false },
  { _id: "TUR", nombre: "Turquia",                confederacion: "UEFA",     grupo: "D", ranking_fifa: 25, participaciones_mundiales:  3, director_tecnico: "Vincenzo Montella",     anfitrion: false },
  { _id: "GER", nombre: "Alemania",               confederacion: "UEFA",     grupo: "E", ranking_fifa:  9, participaciones_mundiales: 20, director_tecnico: "Julian Nagelsmann",     anfitrion: false },
  { _id: "CUW", nombre: "Curazao",                confederacion: "CONCACAF", grupo: "E", ranking_fifa: 63, participaciones_mundiales:  0, director_tecnico: "Dick Advocaat",         anfitrion: false },
  { _id: "CIV", nombre: "Costa de Marfil",        confederacion: "CAF",      grupo: "E", ranking_fifa: 31, participaciones_mundiales:  3, director_tecnico: "Emerse Fae",            anfitrion: false },
  { _id: "ECU", nombre: "Ecuador",                confederacion: "CONMEBOL", grupo: "E", ranking_fifa: 23, participaciones_mundiales:  4, director_tecnico: "Sebastian Beccacece",   anfitrion: false },
  { _id: "NED", nombre: "Paises Bajos",           confederacion: "UEFA",     grupo: "F", ranking_fifa:  7, participaciones_mundiales: 11, director_tecnico: "Ronald Koeman",         anfitrion: false },
  { _id: "JPN", nombre: "Japon",                  confederacion: "AFC",      grupo: "F", ranking_fifa: 18, participaciones_mundiales:  7, director_tecnico: "Hajime Moriyasu",       anfitrion: false },
  { _id: "SWE", nombre: "Suecia",                 confederacion: "UEFA",     grupo: "F", ranking_fifa: 26, participaciones_mundiales: 12, director_tecnico: "Jon Dahl Tomasson",     anfitrion: false },
  { _id: "TUN", nombre: "Tunez",                  confederacion: "CAF",      grupo: "F", ranking_fifa: 41, participaciones_mundiales:  6, director_tecnico: "Sami Trabelsi",         anfitrion: false },
  { _id: "BEL", nombre: "Belgica",                confederacion: "UEFA",     grupo: "G", ranking_fifa:  8, participaciones_mundiales: 14, director_tecnico: "Rudi Garcia",           anfitrion: false },
  { _id: "EGY", nombre: "Egipto",                 confederacion: "CAF",      grupo: "G", ranking_fifa: 33, participaciones_mundiales:  3, director_tecnico: "Hossam Hassan",         anfitrion: false },
  { _id: "IRN", nombre: "Iran",                   confederacion: "AFC",      grupo: "G", ranking_fifa: 20, participaciones_mundiales:  6, director_tecnico: "Amir Ghalenoei",        anfitrion: false },
  { _id: "NZL", nombre: "Nueva Zelanda",          confederacion: "OFC",      grupo: "G", ranking_fifa: 59, participaciones_mundiales:  2, director_tecnico: "Darren Bazeley",        anfitrion: false },
  { _id: "ESP", nombre: "Espana",                 confederacion: "UEFA",     grupo: "H", ranking_fifa:  2, participaciones_mundiales: 16, director_tecnico: "Luis de la Fuente",     anfitrion: true  },
  { _id: "CPV", nombre: "Cabo Verde",             confederacion: "CAF",      grupo: "H", ranking_fifa: 55, participaciones_mundiales:  0, director_tecnico: "Bubista",               anfitrion: false },
  { _id: "KSA", nombre: "Arabia Saudita",         confederacion: "AFC",      grupo: "H", ranking_fifa: 50, participaciones_mundiales:  6, director_tecnico: "Herve Renard",          anfitrion: false },
  { _id: "URU", nombre: "Uruguay",                confederacion: "CONMEBOL", grupo: "H", ranking_fifa: 14, participaciones_mundiales: 14, director_tecnico: "Marcelo Bielsa",        anfitrion: true  },
  { _id: "FRA", nombre: "Francia",                confederacion: "UEFA",     grupo: "I", ranking_fifa:  3, participaciones_mundiales: 16, director_tecnico: "Didier Deschamps",      anfitrion: false },
  { _id: "SEN", nombre: "Senegal",                confederacion: "CAF",      grupo: "I", ranking_fifa: 28, participaciones_mundiales:  3, director_tecnico: "Pape Thiaw",            anfitrion: false },
  { _id: "IRQ", nombre: "Irak",                   confederacion: "AFC",      grupo: "I", ranking_fifa: 51, participaciones_mundiales:  1, director_tecnico: "Graham Arnold",         anfitrion: false },
  { _id: "NOR", nombre: "Noruega",                confederacion: "UEFA",     grupo: "I", ranking_fifa: 35, participaciones_mundiales:  3, director_tecnico: "Stale Solbakken",       anfitrion: false },
  { _id: "ARG", nombre: "Argentina",              confederacion: "CONMEBOL", grupo: "J", ranking_fifa:  1, participaciones_mundiales: 18, director_tecnico: "Lionel Scaloni",        anfitrion: true  },
  { _id: "ALG", nombre: "Argelia",                confederacion: "CAF",      grupo: "J", ranking_fifa: 40, participaciones_mundiales:  4, director_tecnico: "Vladimir Petkovic",     anfitrion: false },
  { _id: "AUT", nombre: "Austria",                confederacion: "UEFA",     grupo: "J", ranking_fifa: 22, participaciones_mundiales:  7, director_tecnico: "Ralf Rangnick",         anfitrion: false },
  { _id: "JOR", nombre: "Jordania",               confederacion: "AFC",      grupo: "J", ranking_fifa: 54, participaciones_mundiales:  0, director_tecnico: "Jamal Sellami",         anfitrion: false },
  { _id: "POR", nombre: "Portugal",               confederacion: "UEFA",     grupo: "K", ranking_fifa:  6, participaciones_mundiales:  8, director_tecnico: "Roberto Martinez",      anfitrion: true  },
  { _id: "COD", nombre: "RD Congo",               confederacion: "CAF",      grupo: "K", ranking_fifa: 56, participaciones_mundiales:  1, director_tecnico: "Sebastien Desabre",     anfitrion: false },
  { _id: "UZB", nombre: "Uzbekistan",             confederacion: "AFC",      grupo: "K", ranking_fifa: 53, participaciones_mundiales:  0, director_tecnico: "Timur Kapadze",         anfitrion: false },
  { _id: "COL", nombre: "Colombia",               confederacion: "CONMEBOL", grupo: "K", ranking_fifa: 13, participaciones_mundiales:  6, director_tecnico: "Nestor Lorenzo",        anfitrion: false },
  { _id: "ENG", nombre: "Inglaterra",             confederacion: "UEFA",     grupo: "L", ranking_fifa:  4, participaciones_mundiales: 16, director_tecnico: "Thomas Tuchel",         anfitrion: false },
  { _id: "CRO", nombre: "Croacia",                confederacion: "UEFA",     grupo: "L", ranking_fifa: 10, participaciones_mundiales:  6, director_tecnico: "Zlatko Dalic",          anfitrion: false },
  { _id: "GHA", nombre: "Ghana",                  confederacion: "CAF",      grupo: "L", ranking_fifa: 45, participaciones_mundiales:  4, director_tecnico: "Otto Addo",             anfitrion: false },
  { _id: "PAN", nombre: "Panama",                 confederacion: "CONCACAF", grupo: "L", ranking_fifa: 34, participaciones_mundiales:  1, director_tecnico: "Thomas Christiansen",   anfitrion: false },
  { _id: "ITA", nombre: "Italia",                 confederacion: "UEFA",     grupo: "M", ranking_fifa: 11, participaciones_mundiales: 18, director_tecnico: "Gennaro Gattuso",       anfitrion: false },
  { _id: "CHI", nombre: "Chile",                  confederacion: "CONMEBOL", grupo: "M", ranking_fifa: 46, participaciones_mundiales:  9, director_tecnico: "Nicolas Cordova",       anfitrion: false },
  { _id: "NGA", nombre: "Nigeria",                confederacion: "CAF",      grupo: "M", ranking_fifa: 47, participaciones_mundiales:  6, director_tecnico: "Eric Chelle",           anfitrion: false },
  { _id: "CHN", nombre: "China",                  confederacion: "AFC",      grupo: "M", ranking_fifa: 61, participaciones_mundiales:  1, director_tecnico: "Dejan Djurdjevic",      anfitrion: false },
  { _id: "DEN", nombre: "Dinamarca",              confederacion: "UEFA",     grupo: "N", ranking_fifa: 19, participaciones_mundiales:  6, director_tecnico: "Brian Riemer",          anfitrion: false },
  { _id: "WAL", nombre: "Gales",                  confederacion: "UEFA",     grupo: "N", ranking_fifa: 29, participaciones_mundiales:  2, director_tecnico: "Craig Bellamy",         anfitrion: false },
  { _id: "PER", nombre: "Peru",                   confederacion: "CONMEBOL", grupo: "N", ranking_fifa: 39, participaciones_mundiales:  5, director_tecnico: "Manuel Barreto",        anfitrion: false },
  { _id: "CMR", nombre: "Camerun",                confederacion: "CAF",      grupo: "N", ranking_fifa: 52, participaciones_mundiales:  8, director_tecnico: "Marc Brys",             anfitrion: false },
  { _id: "POL", nombre: "Polonia",                confederacion: "UEFA",     grupo: "O", ranking_fifa: 30, participaciones_mundiales:  9, director_tecnico: "Jan Urban",             anfitrion: false },
  { _id: "VEN", nombre: "Venezuela",              confederacion: "CONMEBOL", grupo: "O", ranking_fifa: 44, participaciones_mundiales:  0, director_tecnico: "Fernando Batista",      anfitrion: false },
  { _id: "MLI", nombre: "Mali",                   confederacion: "CAF",      grupo: "O", ranking_fifa: 57, participaciones_mundiales:  0, director_tecnico: "Tom Saintfiet",         anfitrion: false },
  { _id: "CRC", nombre: "Costa Rica",             confederacion: "CONCACAF", grupo: "O", ranking_fifa: 49, participaciones_mundiales:  6, director_tecnico: "Miguel Herrera",        anfitrion: false },
  { _id: "SRB", nombre: "Serbia",                 confederacion: "UEFA",     grupo: "P", ranking_fifa: 32, participaciones_mundiales: 12, director_tecnico: "Veljko Paunovic",       anfitrion: false },
  { _id: "UKR", nombre: "Ucrania",                confederacion: "UEFA",     grupo: "P", ranking_fifa: 24, participaciones_mundiales:  1, director_tecnico: "Serhiy Rebrov",         anfitrion: false },
  { _id: "OMA", nombre: "Oman",                   confederacion: "AFC",      grupo: "P", ranking_fifa: 60, participaciones_mundiales:  0, director_tecnico: "Carlos Queiroz",        anfitrion: false },
  { _id: "NCL", nombre: "Nueva Caledonia",        confederacion: "OFC",      grupo: "P", ranking_fifa: 64, participaciones_mundiales:  0, director_tecnico: "Johann Sidaner",        anfitrion: false },
];
